# Generated by Django 5.0.10 on 2026-01-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score_threshold', models.PositiveSmallIntegerField(default=20)),
                ('severity_threshold', models.PositiveSmallIntegerField(default=4)),
                ('store_extracted_text', models.BooleanField(default=False, help_text='Si es False, no se almacena el texto extraído (seguridad)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Política',
                'verbose_name_plural': 'Configuración de Políticas',
            },
        ),
    ]
