# Generated by Django 5.0.10 on 2026-01-22 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finding',
            options={'permissions': [('view_sensitive_finding', 'Puede ver coincidencias completas (sin enmascarar)')]},
        ),
    ]
