# Generated by Django 5.0.10 on 2026-01-21 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('severity', models.PositiveSmallIntegerField(default=3)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACK', 'Acknowledged'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='documents.document')),
            ],
        ),
    ]
