# Generated by Django 5.0.10 on 2026-01-22 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'permissions': [('ack_alert', 'Puede atender/acknowledge alertas')]},
        ),
    ]
